services:
  springtest:
    image: 'springtest:latest'
    container_name: springtest
    build:
      context: .
    # TODO add --no-daemon when https://github.com/gradle/gradle/issues/18508 gets fixed
    command: ./gradlew test
    depends_on:
      - dbsetuptest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbtest:5432/test
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpassword
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
          
  dbtest:
    #image: 'postgres:13.1-alpine'
    image: 'dbpostgrestest:latest'
    container_name: dbtest
      #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./recreate.sh db'
      #environment:
      #- POSTGRES_USER=dbuser
      #- POSTGRES_PASSWORD=dbpassword
      #- POSTGRES_DB=test

  dbsetuptest:
    image: 'dbpostgrestest:latest'
    container_name: dbsetuptest
    depends_on:
      - dbtest
    command: bash -c 'while !</dev/tcp/dbtest/5432; do sleep 1; done; ./recreate.sh dbtest test'

