DROP TABLE IF EXISTS App_Post;
DROP TABLE IF EXISTS App_Thread;
DROP TABLE IF EXISTS App_Category_Role;
DROP TABLE IF EXISTS App_Category;
DROP TABLE IF EXISTS App_User;
DROP TABLE IF EXISTS App_Role;
