spring:
  datasource:
    password: dbpassword
    url: jdbc:postgresql://localhost:5432/demo
    username: dbuser
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          validation:
            # Disable validation on repository.save(entity) because it doesn't inject spring beans
            # into the custom constraint validators. Use @Valid, @Validated or LocalValidatorFactoryBean instead
            mode: none
  data:
    rest:
      detection-strategy: annotated
      default-page-size: 20
      max-page-size: 20
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

app:
  token:
    secret: q4NyfcZa41vhSF4PHPhgDILTJ4sqQW+V7Iup8G6q5Bw=
---

#?stringtype=unspecified

#server.servlet.context-path=/api
#spring.security.oauth2.client.registration.github.client-id=test
#spring.security.oauth2.client.registration.github.client-secret=test

#spring.security.oauth2.resourceserver.jwt.public-key-location=
#spring.security.oauth2.resourceserver.jwt.public-key-location=simple.pub
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/oauth2/jwks

#springdoc.packages-to-scan=com.example.demo.controller